version: "3.8"

services:
  blogging-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: final-project:latest
    ports:
      - "8090:8080"      # host:container
    environment:
      SPRING_PROFILES_ACTIVE: "mysql"
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER:-appuser}
      DB_PASSWORD: ${MYSQL_PASSWORD:-apppass}
      DB_NAME: ${MYSQL_DATABASE:-twitterapp}
      # Java tuning options
      JAVA_OPTS: "-Xms256m -Xmx512m -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE}"
    depends_on:
       db :
         condition: service_healthy
    networks:
      - blogging-network
    restart: unless-stopped

  db:
    image: mysql:9.2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-twitterapp}
      MYSQL_USER: ${MYSQL_USER:-appuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-apppass}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 8
    networks:
      - blogging-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - blogging-app
    networks:
      - blogging-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
    depends_on:
      - prometheus
    networks:
      - blogging-network
    restart: unless-stopped

  sonardb:
    image: postgres:17.5
    environment:
      POSTGRES_USER: ${SONARQUBE_DB_USER:-sonar}
      POSTGRES_PASSWORD: ${SONARQUBE_DB_PASSWORD:-sonarpass}
      POSTGRES_DB: ${SONARQUBE_DB_NAME:-sonar}
    volumes:
      - sonardb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SONARQUBE_DB_USER:-sonar}"]
      interval: 10s
      timeout: 5s
      retries: 8
    networks:
      - blogging-network
    restart: unless-stopped

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonardb:5432/${SONARQUBE_DB_NAME:-sonar}
      SONAR_JDBC_USERNAME: ${SONARQUBE_DB_USER:-sonar}
      SONAR_JDBC_PASSWORD: ${SONARQUBE_DB_PASSWORD:-sonarpass}
    depends_on:
       sonardb:
          condition: service_healthy

    networks:
      - blogging-network
    restart: unless-stopped

  nexus:
    image: sonatype/nexus3:latest
    ports:
      - "8081:8081"
      - "8083:8083"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - blogging-network
    restart: unless-stopped

volumes:
  db_data:
  sonardb_data:
  nexus-data:

networks:
  blogging-network:
    driver: bridge
