global:
  scrape_interval: 15s
  evaluation_interval: 15s
  
scrape_configs:
  - job_name: "blogging-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["blogging-app:8080"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "grafana"
    static_configs:
      - targets: ["localhost:3000"]
  - job_name: "mysql"
    static_configs:
      - targets: ["mysql-exporter:9104"]
  - job_name: "sonar"
    static_configs:
      - targets: ["sonar-exporter:9000"]

